version: 2
references:
  workspace: &workspace
    ~/workspace
  attach_debug_workspace: &attach_debug_workspace
    attach_workspace:
      at: *workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - app/build/intermediates
        - app/build/outputs/androidTest-results
        - app/build/outputs/apk
        - app/build/test-results
        - coroutinebinding/build/intermediates
        - coroutinebinding/build/outputs/androidTest-results
        - coroutinebinding/build/outputs/apk
        - coroutinebinding/build/test-results
        - coroutinebinding/build/reports
        - coroutinebinding-recyclerview/build/intermediates
        - coroutinebinding-recyclerview/build/outputs/androidTest-results
        - coroutinebinding-recyclerview/build/outputs/apk
        - coroutinebinding-recyclerview/build/test-results
        - coroutinebinding-recyclerview/build/reports
        - coroutinebinding-material/build/intermediates
        - coroutinebinding-material/build/outputs/androidTest-results
        - coroutinebinding-material/build/outputs/apk
        - coroutinebinding-material/build/test-results
        - coroutinebinding-material/build/reports
        - coroutinebinding-constraintlayout/build/intermediates
        - coroutinebinding-constraintlayout/build/outputs/androidTest-results
        - coroutinebinding-constraintlayout/build/outputs/apk
        - coroutinebinding-constraintlayout/build/test-results
        - coroutinebinding-constraintlayout/build/reports
  persist_firebase_workspace: &persist_firebase_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - firebase
  prepare_firebase_test_1: &prepare_firebase_test_1
    run:
      name: Create secret json
      command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
  prepare_firebase_test_2: &prepare_firebase_test_2
    run:
      name: Set Project id
      command: gcloud config set project $PROJECT_ID
  prepare_firebase_test_3: &prepare_firebase_test_3
    run:
      name: Gcloud Login
      command: gcloud auth activate-service-account $ACCOUNT --key-file ${HOME}/client-secret.json

jobs:
  build:
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx1600m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "coroutinebinding/build.gradle" }}-{{ checksum  "coroutinebinding-recyclerview/build.gradle" }}-{{ checksum  "coroutinebinding-material/build.gradle" }}-{{ checksum  "coroutinebinding-constraintlayout/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "coroutinebinding/build.gradle" }}-{{ checksum  "coroutinebinding-recyclerview/build.gradle" }}-{{ checksum  "coroutinebinding-material/build.gradle" }}-{{ checksum  "coroutinebinding-constraintlayout/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew :app:assembleDebug assembleAndroidTest -Dorg.gradle.parallel=false
      - *persist_debug_workspace
  firebase_test:
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - *attach_debug_workspace
      - <<: *prepare_firebase_test_1
      - <<: *prepare_firebase_test_2
      - <<: *prepare_firebase_test_3
      - run:
          name: Run test
          command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test coroutinebinding/build/outputs/apk/androidTest/debug/coroutinebinding-debug-androidTest.apk --timeout 5m
      # - *persist_firebase_workspace
      - store_artifacts:
          path: firebase/
          destination: /firebase/
  firebase_test_constraintlayout:
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - *attach_debug_workspace
      - <<: *prepare_firebase_test_1
      - <<: *prepare_firebase_test_2
      - <<: *prepare_firebase_test_3
      - run:
          name: Run test
          command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test coroutinebinding-constraintlayout/build/outputs/apk/androidTest/debug/coroutinebinding-constraintlayout-debug-androidTest.apk --timeout 5m
      # - *persist_firebase_workspace
      - store_artifacts:
          path: firebase/
          destination: /firebase/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - firebase_test:
          requires:
            - build
#      - firebase_test_constraintlayout:
#          requires:
#            - build
